import { Vector3 } from "three";

const POSITIONS = {
  center: [0, 0.5, 10],
  berserk: [180, 0.5, -150],
  hill: [-100, 0.5, 240],
  campfire: [-165, 0.5, -150],
  gow: [70, 0.5, 125],
  lake: [-222.5, 0.5, 170],
  dragonball: [150, 0.5, 80],
} as const;

export const playerConfig = {
  JUMP_BUFFER_DURATION_IN_SECONDS: 0.2,
  MAX_JUMPS: 2,
  JUMP_VELOCITY_IN_METERS_PER_SECOND: 9,
  DOUBLE_JUMP_VELOCITY_IN_METERS_PER_SECOND: 8,
  JUMP_CUT_MULTIPLIER: 0.62,
  JUMP_GROUNDING_LOCK_TIME_IN_SECONDS: 0.08,
  FALL_MULTIPLIER: 2.05,

  LINEAR_DAMPING_IN_INVERSE_SECONDS: 1.15,
  ANGULAR_DAMPING_IN_INVERSE_SECONDS: 0.5,
  RADIUS_IN_METERS: 0.5,
  MASS_IN_KILOGRAMS: 0.5,
  FRICTION: 1,
  RESTITUTION: 0.75,

  WATER_SURFACE_Y_IN_METERS: -0.5,
  WATER_DAMPING_LINEAR_IN_INVERSE_SECONDS: 5.0,
  WATER_DAMPING_ANGULAR_IN_INVERSE_SECONDS: 3.5,
  WATER_MOVEMENT_MULTIPLIER: 0.3,
  BUOYANCY_FORCE_IN_NEWTONS: 7.25,
  WATER_VERTICAL_DAMPING_IN_INVERSE_SECONDS: 0.5,
  WATER_BOB_FORCE_IN_NEWTONS: 2.5,

  GROUND_RAY_START_ABOVE_BOTTOM_IN_METERS: 0.03,
  GROUND_RAY_MAX_DISTANCE_IN_METERS: 0.1,
  GROUND_CONTACT_THRESHOLD_IN_METERS: 0.04,
  BOUNCE_SETTLE_VERTICAL_SPEED_IN_METERS_PER_SECOND: 0.85,

  LIN_VEL_STRENGTH_IN_METERS_PER_SECOND_SQUARED: 90,
  MAX_SPEED_IN_METERS_PER_SECOND: 40,
  AIR_CONTROL_FACTOR: 0.4,
  TURN_SPEED_IN_RADIANS_PER_SECOND: 2.6,
  DRIFT_SPIN_MULTIPLIER: 1.5,

  ACCELERATION_SQUASH_STRENGTH: 0.0045,
  JUMP_STRETCH_STRENGTH: 0.5,
  LANDING_SQUASH_STRENGTH: 0.12,
  IMPACT_SQUASH_STRENGTH: 0.08,
  GROUND_SPEED_SQUASH_STRENGTH: 0.003,
  SQUASH_RECOVERY_SPEED_IN_INVERSE_SECONDS: 14,
  MAX_SQUASH_DEFORMATION: 0.4,
  WATER_SQUASH_MULTIPLIER: 0.25,

  PLAYER_INITIAL_POSITION: new Vector3(...POSITIONS.hill),
  CAMERA_OFFSET: new Vector3(0, 16, 20),
  CAMERA_POSITION_FOLLOW_SPEED_IN_INVERSE_SECONDS: 12,
  CAMERA_TARGET_FOLLOW_SPEED_IN_INVERSE_SECONDS: 18,
  CAMERA_ROTATION_FOLLOW_SPEED_IN_INVERSE_SECONDS: 10,
  UP: new Vector3(0, 1, 0),
  DOWN: new Vector3(0, -1, 0),
  FORWARD: new Vector3(0, 0, -1),
  RESET_Y_IN_METERS: -15,
};
